### PR TITLE
fix: api changes on completion-nvim side

### PR DESCRIPTION
**Pull request by haorenW1025**
Just a small changes on completion-nvim side. I'm planning moving `source.lua` to subdirectory and use `completion.lua` as the main api, so before merging that to master I want to make sure your plugin doesn't just break because of it.
Reference: https://github.com/haorenW1025/completion-nvim/pull/121

### CODE REVIEW

**Comment by vigoux** [comment]
Hi ! We have quite a bit change on our side too, can we merge that afterwards ?

**Comment by haorenW1025** [comment]
Sure. Take your time:)

**Comment by vigoux** [comment]
It should be good now !
I think that this is just a rebase away from being merged ;-)

**Comment by haorenW1025** [comment]
Hmm I'm quite confused now.. How should I do this? Should I fetch the master branch and rebase it into my branch? Sorry for being bad at git...

**Comment by vigoux** [comment]
Or I can do it if you want, maybe that's the easier !

**Comment by haorenW1025** [comment]
Yeah I think it should be easier cause I just modified two lines. Closing this then, please notify me when you're finish! Thanks:)

**Comment by vigoux** [comment]
Should be good now !

**Comment by haorenW1025** [comment]
@vigoux Thanks a lot! Sorry for the inconvenience!

**Comment by vigoux** [comment]
No worry, this is so tiny that is doesn't even bother ! And you are making so much good work !

**Pull request closed without merging**
